python -m bp-informer.main_informer.py \
--model informer \
--data Stock \
--root_path "./bp-informer/data/stock" \
--data_path "res.csv" \
--features MS \
--target price \
--freq "t" \
--seq_len 60 \
--label_len 36 \
--pred_len 12 \
--embed timeF \
--batch_size 12